import cowGhee from "./assets/Cow_Ghee.png";
import flour from "./assets/Khaple_Flour.jpg";
import amplaPrash from "./assets/amplaPrash.jpg";

export const dummyProducts = [
  {
    id: "p1",
    badge: "12%",
    bestSellerBadge: "Best Seller",
    image: cowGhee,
    productName: "A2 Cow Ghee - Desi Gir Cow",
    savingsText: "Your Savings",
    savingsAmount: "250",
    productQuantity: "1000 ml(Glass Bottle)",
    rating: "*****",
    review: "4562 reviews",
    price: "1399",
    addButton: "ADD",
  },
  {
    id: "p2",
    badge: "12%",
    bestSellerBadge: "Best Seller",
    image: flour,
    productName: "Khapli Wheat Flour",
    savingsText: "Your Savings",
    savingsAmount: "300",
    productQuantity: "10 kg",
    rating: "****",
    review: "8975 reviews",
    price: "1999",
    addButton: "ADD",
  },
  {
    id: "p3",
    badge: "12%",
    bestSellerBadge: "Best Seller",
    image: amplaPrash,
    productName: "Ampla Prash",
    savingsText: "Your Savings",
    savingsAmount: "180",
    productQuantity: "2 kg (Glass Bottle)",
    rating: "****",
    review: "3425 reviews",
    price: "2459",
    addButton: "ADD",
  },
  {
    id: "p4",
    badge: "12%",
    bestSellerBadge: "Best Seller",
    image: cowGhee,
    productName: "A2 Cow Ghee - Desi Gir Cow",
    savingsText: "Your Savings",
    savingsAmount: "450",
    productQuantity: "1000 ml(Glass Bottle)",
    rating: "*****",
    review: "2003 reviews",
    price: "1569",
    addButton: "ADD",
  },
];
